#!/usr/bin/expect -f

set timeout 30
set server "root@45.95.234.173"
set password "o-4zWa6SFWUGo,"

spawn ssh $server

expect {
    "password:" {
        send "$password\r"
    }
    "(yes/no)?" {
        send "yes\r"
        expect "password:"
        send "$password\r"
    }
}

expect "# "

send "cd /root/TrustStore\r"
expect "# "

send "bash send-last-order-server.sh\r"
expect "# "

send "exit\r"
expect eof

